### PR TITLE
Fix potential UB concatenating two long slices

### LINKED ISSUE #3: Potential UB
The docs for `slice::from_raw_parts` state:

> The total size of the slice must be no larger than isize::MAX bytes in memory. See the safety documentation of pointer::offset.

Since the internal representation is a *byte* slice, this is equivalent to the `len` being smaller than this limit. However, this crate [only checks](https://github.com/oberien/str-concat/blob/bf6c26041714532b33586b460ce4045978fc1826/src/lib.rs#L45) that the length of `a` is smaller than this limit, not the sum of both strings. This is redundant (because `a.len()` is already guaranteed to be smaller than `isize::max_value()` as it comes from a slice) and not enough to guarantee that `a.len() + b.len()` conforms to the requirements for totally avoiding UB.

So, I'm about to fix this. ~~Can I factor out `concat_slice` in a `pub fn` in the same PR? It is a part of `concat` right now but would be useful on its own.~~ I'll factor out the byte concatentation into a private `fn` and provide arbitrary typed slice concatentation in a separate PR.

### PR DESCRIPTION
**Pull request by 197g**
Two very long slices could potentially make the length of the new slice
exceed the allowed lengths of the new instance. Note that this seems
like a non-practical UB as the length could only be violated by two
slices that fill most of the available address space (more than isize)
obtained somehow to still be occupied adjacent memory.

Refactors out byte slice concatentation to prepare concatentation of
other kinds of byte slices.

Closes: #3

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -71,6 +55,41 @@ pub fn concat<'a>(a: &'a str, b: &'a str) -> Result<&'a str, Error> {
...
+        // https://doc.rust-lang.org/std/primitive.pointer.html#safety-1
+        // * starting pointer in-bounds obviously
+        // * ending pointer one byte past the end of an allocated object
+        // * explicit isize overflow check above
+        // * no wraparound required
+        // why: this is the one byte past the end pointer for the input slice `a`
+        if a_ptr.offset(a_len as isize) != b_ptr {
+            return Err(Error::NotAdjacent);
+        }
+        // UNWRAP: both smaller than isize, can't wrap in usize.
```
Comment (oberien) [inline src/lib.rs:79]: I'd add an explanation here as to *why exactly* this is true in rust. For example in C the same could be UB, because in theory `ptrdiff_t` needs to be one bit larger than `uintptr_t`, because it's able to store any difference between two `uintptr_t`. This doesn't apply in rust due to the below reasons.

```suggestion
        // UNWRAP: both smaller than isize, can't wrap in usize.
        // This is because in rust `usize` and `isize` are both guaranteed to have
        // the same number of bits as a pointer [1]. As `isize` is signed, a `usize`
        // can always store the sum of two positive `isize`.
        // [1]: https://doc.rust-lang.org/reference/types/numeric.html#machine-dependent-integer-types
```

**Review by oberien — CHANGES_REQUESTED** [review]
Good Find! Thanks for the fix.

**Review by oberien — APPROVED** [review]
